export const SEARCH_POKEMON = 'SEARCH_POKEMON';

export const FETCH_POKE_REQUEST = 'FETCH_POKE_REQUEST';

export const FETCH_POKE_FAILURE = 'FETCH_POKE_FAILURE';

export const FETCH_POKE_SUCCESS = 'FETCH_POKE_SUCCESS';

export const SEARCH_POKE_SUCCESS = 'SEARCH_POKE_SUCCESS';
export const SEARCH_POKE_REQUEST = 'SEARCH_POKE_REQUEST';
export const SEARCH_POKE_FAILURE = 'SEARCH_POKE_FAILURE';
export const SEARCH_POKE_CLOSE = 'SEARCH_POKE_CLOSE';




